Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: false